/*
 * EVM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Moralis.EvmApi.Client.FileParameter;
using OpenAPIDateConverter = Moralis.EvmApi.Client.OpenAPIDateConverter;

namespace Moralis.EvmApi.Model
{
    /// <summary>
    /// LogEventByAddress
    /// </summary>
    [DataContract(Name = "logEventByAddress")]
    public partial class LogEventByAddress : IEquatable<LogEventByAddress>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogEventByAddress" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LogEventByAddress() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LogEventByAddress" /> class.
        /// </summary>
        /// <param name="transactionHash">The transaction hash (required).</param>
        /// <param name="address">The address of the contract (required).</param>
        /// <param name="blockTimestamp">The block timestamp (required).</param>
        /// <param name="blockNumber">The block number (required).</param>
        /// <param name="blockHash">The block hash (required).</param>
        /// <param name="data">The data of the log (required).</param>
        /// <param name="topic0">topic0 (required).</param>
        /// <param name="topic1">topic1 (required).</param>
        /// <param name="topic2">topic2 (required).</param>
        /// <param name="topic3">topic3 (required).</param>
        /// <param name="transactionIndex">The Transaction index of the log within the block (required).</param>
        /// <param name="logIndex">The log index of the log within the block (required).</param>
        public LogEventByAddress(string transactionHash = default(string), string address = default(string), string blockTimestamp = default(string), string blockNumber = default(string), string blockHash = default(string), string data = default(string), string topic0 = default(string), string topic1 = default(string), string topic2 = default(string), string topic3 = default(string), int transactionIndex = default(int), int logIndex = default(int))
        {
            // to ensure "transactionHash" is required (not null)
            if (transactionHash == null)
            {
                throw new ArgumentNullException("transactionHash is a required property for LogEventByAddress and cannot be null");
            }
            this.TransactionHash = transactionHash;
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for LogEventByAddress and cannot be null");
            }
            this.Address = address;
            // to ensure "blockTimestamp" is required (not null)
            if (blockTimestamp == null)
            {
                throw new ArgumentNullException("blockTimestamp is a required property for LogEventByAddress and cannot be null");
            }
            this.BlockTimestamp = blockTimestamp;
            // to ensure "blockNumber" is required (not null)
            if (blockNumber == null)
            {
                throw new ArgumentNullException("blockNumber is a required property for LogEventByAddress and cannot be null");
            }
            this.BlockNumber = blockNumber;
            // to ensure "blockHash" is required (not null)
            if (blockHash == null)
            {
                throw new ArgumentNullException("blockHash is a required property for LogEventByAddress and cannot be null");
            }
            this.BlockHash = blockHash;
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for LogEventByAddress and cannot be null");
            }
            this.Data = data;
            // to ensure "topic0" is required (not null)
            if (topic0 == null)
            {
                throw new ArgumentNullException("topic0 is a required property for LogEventByAddress and cannot be null");
            }
            this.Topic0 = topic0;
            // to ensure "topic1" is required (not null)
            if (topic1 == null)
            {
                throw new ArgumentNullException("topic1 is a required property for LogEventByAddress and cannot be null");
            }
            this.Topic1 = topic1;
            // to ensure "topic2" is required (not null)
            if (topic2 == null)
            {
                throw new ArgumentNullException("topic2 is a required property for LogEventByAddress and cannot be null");
            }
            this.Topic2 = topic2;
            // to ensure "topic3" is required (not null)
            if (topic3 == null)
            {
                throw new ArgumentNullException("topic3 is a required property for LogEventByAddress and cannot be null");
            }
            this.Topic3 = topic3;
            this.TransactionIndex = transactionIndex;
            this.LogIndex = logIndex;
        }

        /// <summary>
        /// The transaction hash
        /// </summary>
        /// <value>The transaction hash</value>
        [DataMember(Name = "transaction_hash", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionHash { get; set; }

        /// <summary>
        /// The address of the contract
        /// </summary>
        /// <value>The address of the contract</value>
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = true)]
        public string Address { get; set; }

        /// <summary>
        /// The block timestamp
        /// </summary>
        /// <value>The block timestamp</value>
        [DataMember(Name = "block_timestamp", IsRequired = true, EmitDefaultValue = true)]
        public string BlockTimestamp { get; set; }

        /// <summary>
        /// The block number
        /// </summary>
        /// <value>The block number</value>
        [DataMember(Name = "block_number", IsRequired = true, EmitDefaultValue = true)]
        public string BlockNumber { get; set; }

        /// <summary>
        /// The block hash
        /// </summary>
        /// <value>The block hash</value>
        [DataMember(Name = "block_hash", IsRequired = true, EmitDefaultValue = true)]
        public string BlockHash { get; set; }

        /// <summary>
        /// The data of the log
        /// </summary>
        /// <value>The data of the log</value>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public string Data { get; set; }

        /// <summary>
        /// Gets or Sets Topic0
        /// </summary>
        [DataMember(Name = "topic0", IsRequired = true, EmitDefaultValue = true)]
        public string Topic0 { get; set; }

        /// <summary>
        /// Gets or Sets Topic1
        /// </summary>
        [DataMember(Name = "topic1", IsRequired = true, EmitDefaultValue = true)]
        public string Topic1 { get; set; }

        /// <summary>
        /// Gets or Sets Topic2
        /// </summary>
        [DataMember(Name = "topic2", IsRequired = true, EmitDefaultValue = true)]
        public string Topic2 { get; set; }

        /// <summary>
        /// Gets or Sets Topic3
        /// </summary>
        [DataMember(Name = "topic3", IsRequired = true, EmitDefaultValue = true)]
        public string Topic3 { get; set; }

        /// <summary>
        /// The Transaction index of the log within the block
        /// </summary>
        /// <value>The Transaction index of the log within the block</value>
        [DataMember(Name = "transaction_index", IsRequired = true, EmitDefaultValue = true)]
        public int TransactionIndex { get; set; }

        /// <summary>
        /// The log index of the log within the block
        /// </summary>
        /// <value>The log index of the log within the block</value>
        [DataMember(Name = "log_index", IsRequired = true, EmitDefaultValue = true)]
        public int LogIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogEventByAddress {\n");
            sb.Append("  TransactionHash: ").Append(TransactionHash).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  BlockTimestamp: ").Append(BlockTimestamp).Append("\n");
            sb.Append("  BlockNumber: ").Append(BlockNumber).Append("\n");
            sb.Append("  BlockHash: ").Append(BlockHash).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Topic0: ").Append(Topic0).Append("\n");
            sb.Append("  Topic1: ").Append(Topic1).Append("\n");
            sb.Append("  Topic2: ").Append(Topic2).Append("\n");
            sb.Append("  Topic3: ").Append(Topic3).Append("\n");
            sb.Append("  TransactionIndex: ").Append(TransactionIndex).Append("\n");
            sb.Append("  LogIndex: ").Append(LogIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LogEventByAddress);
        }

        /// <summary>
        /// Returns true if LogEventByAddress instances are equal
        /// </summary>
        /// <param name="input">Instance of LogEventByAddress to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LogEventByAddress input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TransactionHash == input.TransactionHash ||
                    (this.TransactionHash != null &&
                    this.TransactionHash.Equals(input.TransactionHash))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.BlockTimestamp == input.BlockTimestamp ||
                    (this.BlockTimestamp != null &&
                    this.BlockTimestamp.Equals(input.BlockTimestamp))
                ) && 
                (
                    this.BlockNumber == input.BlockNumber ||
                    (this.BlockNumber != null &&
                    this.BlockNumber.Equals(input.BlockNumber))
                ) && 
                (
                    this.BlockHash == input.BlockHash ||
                    (this.BlockHash != null &&
                    this.BlockHash.Equals(input.BlockHash))
                ) && 
                (
                    this.Data == input.Data ||
                    (this.Data != null &&
                    this.Data.Equals(input.Data))
                ) && 
                (
                    this.Topic0 == input.Topic0 ||
                    (this.Topic0 != null &&
                    this.Topic0.Equals(input.Topic0))
                ) && 
                (
                    this.Topic1 == input.Topic1 ||
                    (this.Topic1 != null &&
                    this.Topic1.Equals(input.Topic1))
                ) && 
                (
                    this.Topic2 == input.Topic2 ||
                    (this.Topic2 != null &&
                    this.Topic2.Equals(input.Topic2))
                ) && 
                (
                    this.Topic3 == input.Topic3 ||
                    (this.Topic3 != null &&
                    this.Topic3.Equals(input.Topic3))
                ) && 
                (
                    this.TransactionIndex == input.TransactionIndex ||
                    this.TransactionIndex.Equals(input.TransactionIndex)
                ) && 
                (
                    this.LogIndex == input.LogIndex ||
                    this.LogIndex.Equals(input.LogIndex)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionHash != null)
                {
                    hashCode = (hashCode * 59) + this.TransactionHash.GetHashCode();
                }
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.BlockTimestamp != null)
                {
                    hashCode = (hashCode * 59) + this.BlockTimestamp.GetHashCode();
                }
                if (this.BlockNumber != null)
                {
                    hashCode = (hashCode * 59) + this.BlockNumber.GetHashCode();
                }
                if (this.BlockHash != null)
                {
                    hashCode = (hashCode * 59) + this.BlockHash.GetHashCode();
                }
                if (this.Data != null)
                {
                    hashCode = (hashCode * 59) + this.Data.GetHashCode();
                }
                if (this.Topic0 != null)
                {
                    hashCode = (hashCode * 59) + this.Topic0.GetHashCode();
                }
                if (this.Topic1 != null)
                {
                    hashCode = (hashCode * 59) + this.Topic1.GetHashCode();
                }
                if (this.Topic2 != null)
                {
                    hashCode = (hashCode * 59) + this.Topic2.GetHashCode();
                }
                if (this.Topic3 != null)
                {
                    hashCode = (hashCode * 59) + this.Topic3.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TransactionIndex.GetHashCode();
                hashCode = (hashCode * 59) + this.LogIndex.GetHashCode();
                return hashCode;
            }
        }

    }

}
