/*
 * EVM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Moralis.EvmApi.Client.FileParameter;
using OpenAPIDateConverter = Moralis.EvmApi.Client.OpenAPIDateConverter;

namespace Moralis.EvmApi.Model
{
    /// <summary>
    /// NativeErc20Price
    /// </summary>
    [DataContract(Name = "nativeErc20Price")]
    public partial class NativeErc20Price : IEquatable<NativeErc20Price>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeErc20Price" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NativeErc20Price() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeErc20Price" /> class.
        /// </summary>
        /// <param name="value">The native price of the token (required).</param>
        /// <param name="decimals">The number of decimals on the token (required).</param>
        /// <param name="name">The name of the token (required).</param>
        /// <param name="symbol">The symbol of the token (required).</param>
        public NativeErc20Price(string value = default(string), int decimals = default(int), string name = default(string), string symbol = default(string))
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for NativeErc20Price and cannot be null");
            }
            this.Value = value;
            this.Decimals = decimals;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for NativeErc20Price and cannot be null");
            }
            this.Name = name;
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new ArgumentNullException("symbol is a required property for NativeErc20Price and cannot be null");
            }
            this.Symbol = symbol;
        }

        /// <summary>
        /// The native price of the token
        /// </summary>
        /// <value>The native price of the token</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// The number of decimals on the token
        /// </summary>
        /// <value>The number of decimals on the token</value>
        [DataMember(Name = "decimals", IsRequired = true, EmitDefaultValue = true)]
        public int Decimals { get; set; }

        /// <summary>
        /// The name of the token
        /// </summary>
        /// <value>The name of the token</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The symbol of the token
        /// </summary>
        /// <value>The symbol of the token</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public string Symbol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NativeErc20Price {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Decimals: ").Append(Decimals).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NativeErc20Price);
        }

        /// <summary>
        /// Returns true if NativeErc20Price instances are equal
        /// </summary>
        /// <param name="input">Instance of NativeErc20Price to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NativeErc20Price input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.Decimals == input.Decimals ||
                    this.Decimals.Equals(input.Decimals)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Decimals.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Symbol != null)
                {
                    hashCode = (hashCode * 59) + this.Symbol.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
