/*
 * EVM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Moralis.EvmApi.Client.FileParameter;
using OpenAPIDateConverter = Moralis.EvmApi.Client.OpenAPIDateConverter;

namespace Moralis.EvmApi.Model
{
    /// <summary>
    /// NativeBalancesInnerWalletBalancesInner
    /// </summary>
    [DataContract(Name = "nativeBalances_inner_wallet_balances_inner")]
    public partial class NativeBalancesInnerWalletBalancesInner : IEquatable<NativeBalancesInnerWalletBalancesInner>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeBalancesInnerWalletBalancesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NativeBalancesInnerWalletBalancesInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeBalancesInnerWalletBalancesInner" /> class.
        /// </summary>
        /// <param name="address">address (required).</param>
        /// <param name="balance">balance (required).</param>
        /// <param name="balanceFormatted">balance formatted (required).</param>
        public NativeBalancesInnerWalletBalancesInner(string address = default(string), string balance = default(string), string balanceFormatted = default(string))
        {
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for NativeBalancesInnerWalletBalancesInner and cannot be null");
            }
            this.Address = address;
            // to ensure "balance" is required (not null)
            if (balance == null)
            {
                throw new ArgumentNullException("balance is a required property for NativeBalancesInnerWalletBalancesInner and cannot be null");
            }
            this.Balance = balance;
            // to ensure "balanceFormatted" is required (not null)
            if (balanceFormatted == null)
            {
                throw new ArgumentNullException("balanceFormatted is a required property for NativeBalancesInnerWalletBalancesInner and cannot be null");
            }
            this.BalanceFormatted = balanceFormatted;
        }

        /// <summary>
        /// address
        /// </summary>
        /// <value>address</value>
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = true)]
        public string Address { get; set; }

        /// <summary>
        /// balance
        /// </summary>
        /// <value>balance</value>
        [DataMember(Name = "balance", IsRequired = true, EmitDefaultValue = true)]
        public string Balance { get; set; }

        /// <summary>
        /// balance formatted
        /// </summary>
        /// <value>balance formatted</value>
        [DataMember(Name = "balance_formatted", IsRequired = true, EmitDefaultValue = true)]
        public string BalanceFormatted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NativeBalancesInnerWalletBalancesInner {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("  BalanceFormatted: ").Append(BalanceFormatted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NativeBalancesInnerWalletBalancesInner);
        }

        /// <summary>
        /// Returns true if NativeBalancesInnerWalletBalancesInner instances are equal
        /// </summary>
        /// <param name="input">Instance of NativeBalancesInnerWalletBalancesInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NativeBalancesInnerWalletBalancesInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.Balance == input.Balance ||
                    (this.Balance != null &&
                    this.Balance.Equals(input.Balance))
                ) && 
                (
                    this.BalanceFormatted == input.BalanceFormatted ||
                    (this.BalanceFormatted != null &&
                    this.BalanceFormatted.Equals(input.BalanceFormatted))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.Balance != null)
                {
                    hashCode = (hashCode * 59) + this.Balance.GetHashCode();
                }
                if (this.BalanceFormatted != null)
                {
                    hashCode = (hashCode * 59) + this.BalanceFormatted.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
